require 'redmine_meeting_room_calendar/hooks/view_issues_form_details_icalendar'
require 'redmine_meeting_room_calendar/hooks/view_issues_form_details_attendees'
require 'redmine_meeting_room_calendar/hooks/view_issues_form_details_notes'